spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bookstore
    username: test
    password: test
  liquibase:
    url: jdbc:postgresql://localhost:5432/bookstore
    user: test
    password: test
    contexts: dev
springdoc:
  api-docs:
    path: /api-docs